// SPDX-License-Identifier: GPL-3.0-or-later
import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const APP = new URL("../", import.meta.url);
const MQTT_APPS = new URL("../", APP);

test("user documentation covers installation, privacy, configuration, and troubleshooting", async () => {
  const readme = await readFile(new URL("docs/README.md", APP), "utf8");
  for (const phrase of [
    "Node.js 20",
    "XHS_BRIDGE_TOKEN",
    "MQTT_HOST",
    "TC002_MQTT_TOPIC",
    "chrome://extensions",
    "加载已解压的扩展程序",
    "不读取 Cookie",
    "故障排查",
    "127.0.0.1",
    "npm test",
  ]) {
    assert.ok(readme.includes(phrase), `README should mention ${phrase}`);
  }
});

test("preview is a real 52 by 16 PNG generated by the renderer", async () => {
  const png = await readFile(new URL("preview/demo.png", APP));
  assert.deepEqual(png.subarray(0, 8), Buffer.from("89504e470d0a1a0a", "hex"));
  assert.equal(png.readUInt32BE(16), 52);
  assert.equal(png.readUInt32BE(20), 16);
});

test("application is indexed and declares GPL licensing", async () => {
  const index = await readFile(new URL("README.md", MQTT_APPS), "utf8");
  const appReadme = await readFile(new URL("README.md", APP), "utf8");
  const license = await readFile(new URL("docs/LICENSE", APP), "utf8");
  assert.match(index, /xiaohongshu-follower-counter/);
  assert.match(appReadme, /GPL-3\.0-or-later/);
  assert.match(license, /GPL-3\.0-or-later/);
});
